name: Comment when opened
on: issue_comment
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
      issues: write
    steps:
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE: ${{ github.event.issue.html_url }}
        run: |
          $Issue = gh issue list --state "open" --search "hash:3bad9d1217a7985063b5e9b5fd4622280f7eebbdaaa435b8eca7cb85709e4b15" --limit 1 --json
          Write-Host $Issue
